### ISSUE TITLE
Integrar novas ferramentas para análise

### ISSUE THREAD

**Issue by kakanetwork** [kakanetwork/Kyrios#10]
Integração com as ferramentas de terceiros para análises.
Ex: VirusTotal

Atribuído - @JoJoseB

**Comment by JoJoseB** [comment]
Aprimorando o dockerfile que sera utilizado como imagem base das analises, utilizando como boas praticas a fonte: https://scalefactory.com/blog/2020/07/06/the-12-factor-container/

**Comment by JoJoseB** [comment]
Imagens dos resultados obtidos nessa sprint
![Screenshot_20240822_134108](https://github.com/user-attachments/assets/f1dbe50a-1908-4c86-82e2-b0ac35d58ec9)
![Screenshot_20240822_133918](https://github.com/user-attachments/assets/6be8d95a-db97-498c-b0be-a67b2f98c701)
![Screenshot_20240822_133402](https://github.com/user-attachments/assets/19b95570-8495-4dcf-afae-97e0b0dc4e08)
