### ISSUE TITLE
Testar e Validar a plataforma.

### ISSUE THREAD

**Issue by kakanetwork** [kakanetwork/Kyrios#13]
Realizar testes em todas as camadas da plataforma, incluindo a análise de malwares.

Atribuído - @JoJoseB

**Comment by JoJoseB** [comment]
Após uma bateria de testes utilizandos SAMPLES dos seguintes bancos [Not So Boring Android Malware Samples](https://maldroid.github.io/android-malware-samples/), [Conteúdos do livro Android Malware Handbook](https://github.com/android-malware-ml-book/book-content.) Fica evidenciado os seguintes problemas:

- Não é possível analises dinâmicas seguidas
- Não é possível analises simultaneas de diversos usuários da plataforma web
- Há algumas falhas na obtenção de dados da API VirusTotal
- Algumas APK's compilado para certas arquiteturas não conseguem passar pela analise dinâmica
