### ISSUE TITLE
Criação do Banco de dados e Configuração Básica

### ISSUE THREAD

**Issue by kakanetwork** [kakanetwork/Kyrios#6]
Realizar a configuração do Banco de Dados e sua configuração Básica.

Atribuído - @JoJoseB

**Comment by JoJoseB** [comment]
O Commit foi referente a criação do banco de dados com o SGBD postgreSQL, do qual irá servir como backend do nosso projeto

**Comment by JoJoseB** [comment]
segue a lista com os comandos utilizados:
sudo apt-get update
sudo apt-get upgrade

# Configuração Postgresql
sudo apt-get install postgresql postgresql-contrib
sudo adduser --system --group --no-create-home postgres
sudo -i -u postgres
psql
    CREATE USER srv_django WITH PASSWORD 'senha';
    CREATE DATABASE dbdjango OWNER srv_django;
    GRANT ALL PRIVILEGES ON DATABASE dbdjango TO srv_django;

**Comment by JoJoseB** [comment]
Saída do comando sudo systemctl status postgresql 
● postgresql.service - PostgreSQL RDBMS
     Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; preset: enabled)
     Active: active (exited) since Mon 2024-08-05 16:26:16 -03; 17s ago
   Main PID: 22953 (code=exited, status=0/SUCCESS)
        CPU: 1ms

ago 05 16:26:16 jose-debian systemd[1]: Starting postgresql.service - PostgreSQL RDBMS...
ago 05 16:26:16 jose-debian systemd[1]: Finished postgresql.service - PostgreSQL RDBMS.
